# Generated by Django 4.0 on 2023-04-01 22:05

from django.db import migrations, models
import django.utils.timezone
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=255, null=True, unique=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to=events.models.path_and_rename)),
                ('content', models.TextField(blank=True, default='', null=True)),
                ('featured', models.BooleanField(blank=True, default=False)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
