# Generated by Django 4.0 on 2023-04-01 22:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nominations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardCallbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('reason', models.TextField(blank=True, default='', null=True)),
                ('transactionid', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('clienttransid', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('clientreference', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('statusdate', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('brandtransid', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashoutCallbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('clienttransid', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('clientreference', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('telcotransid', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('transactionid', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('reason', models.TextField(blank=True, default='', null=True)),
                ('statusdate', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HubtelCallbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('responseCode', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('data', models.TextField(blank=True, default='', null=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MyBusinessPayPaymentCallbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('payment_date', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('reference', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('status_code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('charge', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tokenized', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('source', models.TextField(blank=True, default='', null=True)),
                ('source_object', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('source_type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('source_number', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('source_reference', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('amount', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('transaction_uuid', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('amount_after_charge', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('processor_transaction_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('error_fields', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('metadata', models.TextField(blank=True, default='', null=True)),
                ('metadata_order_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('metadata_product_description', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_processor', models.CharField(blank=True, choices=[('redde', 'redde'), ('mybusinesspay', 'mybusinesspay'), ('paypal', 'paypal'), ('hubtel', 'hubtel')], default='redde', max_length=100, null=True)),
                ('paymenttype', models.CharField(blank=True, choices=[('ussd', 'ussd'), ('card', 'card'), ('paypal', 'paypal')], default='ussd', max_length=100, null=True)),
                ('clientrefid', models.UUIDField(default=uuid.uuid4)),
                ('clienttransid', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('valuename', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('value', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('custom_code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('payer_fullname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('payer_phonenumber', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('payer_email', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('datepaid', models.DateField(blank=True, default='2020-01-01', null=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionid', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('grossamount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transactionamount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('netamount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('nomination', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_nomination', to='nominations.nominations')),
                ('request', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_request', to='votes.paymentrequests')),
            ],
        ),
        migrations.CreateModel(
            name='USSDCallbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('clienttransid', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('clientreference', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('telcotransid', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('transactionid', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('reason', models.TextField(blank=True, default='', null=True)),
                ('statusdate', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoteSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('session_id', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('mode', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('msisdn', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('userdata', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('response_to_user', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('trafficid', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('other', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('nominee_code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('session_step', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WigalCallbacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('clienttransid', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('clientreference', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('telcotransid', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('transactionid', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('brandtransid', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('reason', models.TextField(blank=True, default='', null=True)),
                ('statusdate', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votecount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('nomination', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes_nomination', to='nominations.nominations')),
                ('payment', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes_payment', to='votes.payments')),
            ],
        ),
    ]
