# Generated by Django 4.0 on 2023-04-01 22:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import nominations.models
import nominations.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AwardSchemes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('theme', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=nominations.models.path_and_rename, validators=[nominations.validators.validate_file_size])),
                ('latest', models.BooleanField(blank=True, default=True)),
                ('nominationopen', models.BooleanField(blank=True, default=True)),
                ('votingopen', models.BooleanField(blank=True, default=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='NominationCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description_short', models.TextField(blank=True, default='', null=True)),
                ('description_long', models.TextField(blank=True, default='', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=nominations.models.path_and_rename, validators=[nominations.validators.validate_file_size])),
                ('active', models.BooleanField(blank=True, default=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheme', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominations_awardscheme', to='nominations.awardschemes')),
            ],
        ),
        migrations.CreateModel(
            name='Nominations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencenumber', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('nominee_photograph', models.ImageField(blank=True, default='', max_length=255, null=True, upload_to=nominations.models.path_and_rename, validators=[nominations.validators.validate_image_size])),
                ('nominee_firstname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nominee_middlename', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nominee_lastname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nominee_phonenumber', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nominee_emailaddress', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('nominee_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=100, null=True)),
                ('nominee_agegroup', models.CharField(blank=True, choices=[('10-20', '10-20'), ('20-30', '20-30'), ('30-40', '30-40'), ('40-50', '40-50'), ('50-60', '50-60'), ('60-70', '60-70'), ('70-80', '70-80'), ('80-90', '80-90'), ('90-100', '90-100')], default='30-40', max_length=100, null=True)),
                ('nominee_bio', models.TextField(blank=True, default='', null=True)),
                ('nominee_deserve_info', models.TextField(blank=True, default='', null=True)),
                ('nominee_effort_info', models.TextField(blank=True, default='', null=True)),
                ('nominee_turning_point', models.TextField(blank=True, default='', null=True)),
                ('nominee_exception', models.TextField(blank=True, default='', null=True)),
                ('nominee_reference_links', models.TextField(blank=True, default='', null=True)),
                ('nominee_towncity', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nominee_region', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nominee_country', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nominee_code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('company_logo', models.ImageField(blank=True, default='', max_length=255, null=True, upload_to=nominations.models.path_and_rename, validators=[nominations.validators.validate_image_size])),
                ('company_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('company_industry', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('company_bio', models.TextField(blank=True, default='', null=True)),
                ('nominator_fullname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nominator_phonenumber', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nominator_emailaddress', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('nominator_bio', models.TextField(blank=True, default='', null=True)),
                ('nominator_knownnominee_time', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nominator_nominee_relationship', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('shortlisted', models.BooleanField(blank=True, default=False)),
                ('approved', models.BooleanField(blank=True, default=False)),
                ('votable', models.BooleanField(blank=True, default=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominations_category', to='nominations.nominationcategories')),
            ],
        ),
    ]
