# Generated by Django 4.0 on 2024-03-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nominations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominations',
            name='nominee_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('NGO', 'NGO')], default='Female', max_length=100, null=True),
        ),
    ]
