# Generated by Django 4.0 on 2023-04-01 22:05

import accounts.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('photograph', models.ImageField(blank=True, null=True, upload_to=accounts.models.path_and_rename)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=50, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('confirmed', models.BooleanField(blank=True, default=False)),
                ('pastfirsttime', models.BooleanField(blank=True, default=False)),
                ('admin', models.BooleanField(blank=True, default=False)),
                ('active', models.BooleanField(blank=True, default=False)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_user', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('nicename', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('iso', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('iso3', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('numcode', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('phonecode', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('minimum_nsn', models.IntegerField(blank=True, default=7, null=True)),
                ('maximum_nsn', models.IntegerField(blank=True, default=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('emailaddress', models.EmailField(blank=True, default='', max_length=255, null=True)),
                ('code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('expired_date', models.BigIntegerField(blank=True, default=0, null=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Telephony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countrycode', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('nowithcountrycode', models.IntegerField(blank=True, null=True)),
                ('nowithoutcountrycode', models.IntegerField(blank=True, null=True)),
                ('supportednetworks', models.CharField(blank=True, max_length=200, null=True)),
                ('nonetstartwith', models.IntegerField(blank=True, null=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField(blank=True, null=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_user', to='accounts.accounts')),
            ],
        ),
    ]
