# Generated by Django 4.0 on 2023-04-01 22:05

import blog.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Title')),
                ('artcover', models.ImageField(blank=True, max_length=255, null=True, upload_to=blog.models.path_and_rename, verbose_name='Art Cover')),
                ('author', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Author')),
                ('location', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Location')),
                ('link', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Link')),
                ('content', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('date', models.DateField(null=True, verbose_name='Date Posted')),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
