# Generated by Django 4.0 on 2023-04-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Title'),
        ),
    ]
