# Generated by Django 4.0 on 2023-04-01 22:05

from django.db import migrations, models
import django.utils.timezone
import index.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('subscriptionstatus', models.BooleanField(blank=True, default=False, max_length=255)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Galleries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=index.models.path_and_rename)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HAGTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('photograph', models.ImageField(blank=True, max_length=255, null=True, upload_to=index.models.path_and_rename)),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True)),
                ('teammember', models.BooleanField(blank=True, default=False)),
                ('boardmember', models.BooleanField(blank=True, default=False)),
                ('order_id', models.IntegerField(blank=True, default=1, null=True)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('subinfo', models.CharField(blank=True, max_length=255, null=True)),
                ('testimony', models.TextField(blank=True, null=True)),
                ('photograph', models.ImageField(blank=True, max_length=255, null=True, upload_to=index.models.path_and_rename)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('datecreated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
